/**
 * Auth
 */
export const LOGIN_USER_REQUESTED = 'LOGIN_USER_REQUESTED';
export const LOGIN_USER_SUCCESS = 'LOGIN_USER_SUCCESS';
export const LOGIN_USER_FAILURE = 'LOGIN_USER_FAILURE';

export const GET_CURRENT_USER_REQUESTED = 'GET_CURRENT_USER_REQUESTED'
export const GET_CURRENT_USER_SUCCESS = 'GET_CURRENT_USER_SUCCESS'
export const GET_CURRENT_USER_FAILURE = 'GET_CURRENT_USER_FAILURE'

export const SIGN_UP_USER_REQUESTED = 'SIGN_UP_USER_REQUESTED';
export const SIGN_UP_USER_SUCCESS = 'SIGN_UP_USER_SUCCESS';
export const SIGN_UP_USER_FAILURE = 'SIGN_UP_USER_FAILURE';

export const CONFIRM_SIGN_UP_REQUESTED = 'CONFIRM_SIGN_UP_REQUESTED';
export const CONFIRM_SIGN_UP_SUCCESS = 'CONFIRM_SIGN_UP_SUCCESS';
export const CONFIRM_SIGN_UP_FAILURE = 'CONFIRM_SIGN_UP_FAILURE';

export const SIGN_OUT_USER_REQUESTED = 'SIGN_OUT_USER_REQUESTED';
export const SIGN_OUT_USER_SUCCESS = 'SIGN_OUT_USER_SUCCESS';
export const SIGN_OUT_USER_FAILURE = 'SIGN_OUT_USER_FAILURE';

export const INITIAL_LOGIN_REQUESTED = 'INITIAL_LOGIN_REQUESTED';
export const INITIAL_LOGIN_SUCCESS = 'INITIAL_LOGIN_SUCCESS';
export const INITIAL_LOGIN_FAILURE = 'INITIAL_LOGIN_FAILURE';

export const TOGGLE_PENDING_CONFIRM_ACCOUNT = 'TOGGLE_PENDING_CONFIRM_ACCOUNT';

/**
* Player
*/

export const GET_PLAYER_DATA_REQUESTED = 'GET_PLAYER_DATA_REQUESTED';
export const GET_PLAYER_DATA_SUCCESS = 'GET_PLAYER_DATA_SUCCESS';
export const GET_PLAYER_DATA_FAILURE = 'GET_PLAYER_DATA_FAILURE';

export const UPDATE_PLAYER_DATA_REQUESTED = 'UPDATE_PLAYER_DATA_REQUESTED';
export const UPDATE_PLAYER_DATA_SUCCESS = 'UPDATE_PLAYER_DATA_SUCCESS';
export const UPDATE_PLAYER_DATA_FAILURE = 'UPDATE_PLAYER_DATA_FAILURE';

export const GET_PLAYERS_DATA_REQUESTED = 'GET_PLAYERS_DATA_REQUESTED';
export const GET_PLAYERS_DATA_SUCCESS = 'GET_PLAYERS_DATA_SUCCESS';
export const GET_PLAYERS_DATA_FAILURE = 'GET_PLAYERS_DATA_FAILURE';
