/**
 * Boiler
 */
export const GET_DATA_REQUESTED = 'GET_DATA_REQUESTED';
export const GET_DATA_SUCCESS = 'GET_DATA_SUCCESS';
export const GET_DATA_FAILURE = 'GET_DATA_FAILURE';

export const CLEAR_DATA = 'CLEAR_DATA';

/**
 * Auth
 */
export const LOGIN_USER_REQUESTED = 'LOGIN_USER_REQUESTED';
export const LOGIN_USER_SUCCESS = 'LOGIN_USER_SUCCESS';
export const LOGIN_USER_FAILURE = 'LOGIN_USER_FAILURE';

export const GET_CURRENT_USER_REQUESTED = 'GET_CURRENT_USER_REQUESTED'
export const GET_CURRENT_USER_SUCCESS = 'GET_CURRENT_USER_SUCCESS'
export const GET_CURRENT_USER_FAILURE = 'GET_CURRENT_USER_FAILURE'

export const SIGN_OUT_USER_REQUESTED = 'SIGN_OUT_USER_REQUESTED';
export const SIGN_OUT_USER_SUCCESS = 'SIGN_OUT_USER_SUCCESS';
export const SIGN_OUT_USER_FAILURE = 'SIGN_OUT_USER_FAILURE';
